spring:
  application:
    name: ruyuan-eshop-wms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  port: 8008

dubbo:
  scan:
    base-packages: com.ruyuan.eshop.wms.api
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28088
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
